-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.2
    hooks:
    -   id: reorder-python-imports
